theme = "dark"

[editor]
line-number = "relative"
mouse = false
completion-timeout = 5
completion-trigger-len = 1
color-modes = true
cursorline = true
auto-format = true
bufferline = "always"
# jump-label-alphabet = " asdfghjkl;qwertyuiopzxcvbnm,."
jump-label-alphabet = "jfkdls;a urieowpqnvmc,x.zhgytb"
# rulers = [80]

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
"'" = "'"
'`' = '`'
'<' = '>'

[editor.statusline]
left = ["mode", "selections", "diagnostics", "spinner"]
center = []
right = ["position-percentage", "file-name", "version-control", "spacer"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-messages = true

[editor.cursor-shape]
insert = "bar"
normal = "block"

[editor.file-picker]
hidden = false
# ignore = false
# git-ignore = false

[editor.indent-guides]
render = true
# character = "â–"

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "disable"

[editor.soft-wrap]
enable = true

[keys.normal]
"C-l" = ":bn"
"C-h" = ":bp"
"f" = "goto_word"

[keys.normal.space]
"f" = "file_picker_in_current_directory"
"F" = "file_picker_in_current_buffer_directory"
"e" = [
  ':sh rm -f /tmp/unique-file',
  ':insert-output yazi %{buffer_name} --chooser-file=/tmp/unique-file',
  ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/unique-file}',
  ':redraw',
]
"E" = "file_explorer_in_current_buffer_directory"
"y" = ":clipboard-yank-join" # Join and yank selections to clipboard

[keys.select.space]
"y" = ":clipboard-yank-join" # Join and yank selections to clipboard
